"""Added Visitor Model

Revision ID: 03cf2774248e
Revises: ff40b9b7d153
Create Date: 2025-03-25 10:26:14.963929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03cf2774248e'
down_revision: Union[str, None] = 'ff40b9b7d153'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_id'), 'visitors', ['id'], unique=False)
    op.create_index(op.f('ix_visitors_ip'), 'visitors', ['ip'], unique=False)
    op.create_index(op.f('ix_visitors_unique_id'), 'visitors', ['unique_id'], unique=True)
    op.create_table('websites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=True)
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.drop_index('ix_users_phone_number', table_name='users')
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_users_phone_number', 'users', ['phone_number'], unique=True)
    op.drop_column('users', 'hashed_password')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_visitors_unique_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_ip'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_id'), table_name='visitors')
    op.drop_table('visitors')
    # ### end Alembic commands ###
