"""Added few more columns in alaytics model

Revision ID: 312d8d3ed997
Revises: 41db6f50a867
Create Date: 2025-04-26 16:59:20.026185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '312d8d3ed997'
down_revision: Union[str, None] = '41db6f50a867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'country')
    op.add_column('user_locations', sa.Column('analytics_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'user_locations', 'analytics', ['analytics_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_locations', type_='foreignkey')
    op.drop_column('user_locations', 'analytics_id')
    op.add_column('analytics', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
