"""Added few more columns in alaytics model

Revision ID: 41db6f50a867
Revises: 1520f919b219
Create Date: 2025-04-26 15:34:12.445204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41db6f50a867'
down_revision: Union[str, None] = '1520f919b219'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('current_page_path', sa.String(), nullable=True))
    op.add_column('analytics', sa.Column('domain_name', sa.String(), nullable=True))
    op.add_column('analytics', sa.Column('browser_secondary', sa.String(), nullable=True))
    op.add_column('analytics', sa.Column('page_height', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'page_height')
    op.drop_column('analytics', 'browser_secondary')
    op.drop_column('analytics', 'domain_name')
    op.drop_column('analytics', 'current_page_path')
    # ### end Alembic commands ###
