"""Updated Visitor Model

Revision ID: 9206ddc4df63
Revises: 03cf2774248e
Create Date: 2025-03-25 10:28:41.871623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9206ddc4df63'
down_revision: Union[str, None] = '03cf2774248e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('first_visit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('visitors', sa.Column('last_visit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.drop_column('visitors', 'created_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitors', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('visitors', 'last_visit')
    op.drop_column('visitors', 'first_visit')
    # ### end Alembic commands ###
