"""Auto generate all models

Revision ID: ac14ff76461f
Revises: 
Create Date: 2025-04-26 13:25:54.271853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac14ff76461f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('visitors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('unique_id', sa.String(), nullable=True),
    sa.Column('first_visit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_visit', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitors_id'), 'visitors', ['id'], unique=False)
    op.create_index(op.f('ix_visitors_unique_id'), 'visitors', ['unique_id'], unique=True)
    op.create_table('websites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_websites_domain'), 'websites', ['domain'], unique=True)
    op.create_index(op.f('ix_websites_id'), 'websites', ['id'], unique=False)
    op.create_table('analytics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('website_id', sa.UUID(), nullable=True),
    sa.Column('visitor_id', sa.UUID(), nullable=True),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('landing_page', sa.String(), nullable=True),
    sa.Column('session_duration', sa.Float(), nullable=True),
    sa.Column('scroll_depth', sa.Float(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('ipv6', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['visitor_id'], ['visitors.id'], ),
    sa.ForeignKeyConstraint(['website_id'], ['websites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_ip'), 'analytics', ['ip'], unique=False)
    op.create_index(op.f('ix_analytics_ipv6'), 'analytics', ['ipv6'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analytics_ipv6'), table_name='analytics')
    op.drop_index(op.f('ix_analytics_ip'), table_name='analytics')
    op.drop_table('analytics')
    op.drop_index(op.f('ix_websites_id'), table_name='websites')
    op.drop_index(op.f('ix_websites_domain'), table_name='websites')
    op.drop_table('websites')
    op.drop_index(op.f('ix_visitors_unique_id'), table_name='visitors')
    op.drop_index(op.f('ix_visitors_id'), table_name='visitors')
    op.drop_table('visitors')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
