"""Added visitor_session_id in alytics model

Revision ID: f6b27dd7fa96
Revises: ac14ff76461f
Create Date: 2025-04-26 14:37:26.235972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b27dd7fa96'
down_revision: Union[str, None] = 'ac14ff76461f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics', sa.Column('visitor_session_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analytics', 'visitor_session_id')
    # ### end Alembic commands ###
